#!/bin/sh

# must have LUN0
BACKSTORE0=/usr0/var/osd-tgt/tgt-0/
# Optional additional LUNes here
BACKSTORE1=/usr0/var/osd-tgt/tgt-1/
BACKSTORE2=/usr0/var/osd-tgt/tgt-2/
BACKSTORE3=/usr0/var/osd-tgt/tgt-3/

TGTADM=./tgt/usr/tgtadm
# -f - forgraound
# -d - debug level
# DEBUG="-d 9"
DEBUG=""

./tgt/usr/tgtd $DEBUG -f &

sleep 2
$TGTADM --lld iscsi --mode target --op new --tid 1 --targetname $(hostname)
$TGTADM --lld iscsi --mode target \
	--op bind --tid 1 --initiator-address ALL

$TGTADM --lld iscsi --mode logicalunit \
	--op new --tid 1 --lun 0 --bstype=osdemu --device-type osd \
	--backing-store $BACKSTORE0

if [ -n $BACKSTORE1 ]; then
	$TGTADM --lld iscsi --mode logicalunit \
		--op new --tid 1 --lun 1 --bstype=osdemu --device-type osd \
		--backing-store $BACKSTORE1
fi

if [ -n $BACKSTORE2 ]; then
	$TGTADM --lld iscsi --mode logicalunit \
		--op new --tid 1 --lun 2 --bstype=osdemu --device-type osd \
		--backing-store $BACKSTORE2
fi

if [ -n $BACKSTORE3 ]; then
	$TGTADM --lld iscsi --mode logicalunit \
		--op new --tid 1 --lun 3 --bstype=osdemu --device-type osd \
		--backing-store $BACKSTORE3
fi

$TGTADM --lld iscsi --mode target --op show
wait
