#!/bin/bash

for j in 1 2 3 4 5 6 7 8 9 22 23 24
do 
    rm -f out_$j
    echo ./contention $j
    for ((i=1; i<=25; i++)); 
    do 
	mpiexec --pernode -np $i ./contention $j >> out_$j; 
    done; 
done
