/*************************************************************
** Copyright 2004, 2005. IBM Corp.** All Rights Reserved.***
**************************************************************
** Redistribution and use in source and binary forms, with or without
** modifications, are permitted provided that the following conditions 
** are met:
** 
** i.  Redistribution of source code must retain the above copyright
**     notice, this list of conditions and the following disclaimer.
**
** ii. Redistribution in binary form must reproduce the above copyright 
**     notice, this list of conditions and the following disclaimer in the 
**     documentation and/or other materials provided with the distribution.
**
** iii.Neither the name(s) of IBM Corp.** nor the names of its/their
**     contributors may be used to endorse or promote products derived
**     from this software without specific prior written permission.
*******************************************************************
** THIS SOFTWARE IS PROVIDED BY IBM CORP. AND CONTRIBUTORS "AS IS" 
** AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING , BUT NOT LIMITED
** TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A 
** PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE IBM
** CORP. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
** INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
** (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS 
** OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
** HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
** STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED 
** OF THE POSSIBILITY OF SUCH DAMAGE.
** 
*****************************************************************************
*****************************************************************************/
#define OSD_MAX_ATTR_SIZE 65 
#define OSD_PAGE_NUM_ROOT_DIRECTORY PAGE_R+0     
#define OSD_ATTR_NUM_ROOT_DIRECTORY_page_id PAGE_R+0     
#define OSD_ATTR_NUM_ROOT_DIRECTORY_A1 PAGE_R+1     
#define OSD_ATTR_NUM_ROOT_DIRECTORY_A2 PAGE_R+2     
#define OSD_ATTR_NUM_ROOT_DIRECTORY_A3 PAGE_R+3     
#define OSD_ATTR_NUM_ROOT_DIRECTORY_A5 PAGE_R+5     
#define OSD_PAGE_NUM_PART_DIRECTORY PAGE_P+0     
#define OSD_ATTR_NUM_PART_DIRECTORY_page_id PAGE_P+0     
#define OSD_ATTR_NUM_PART_DIRECTORY_A1 PAGE_P+1     
#define OSD_ATTR_NUM_PART_DIRECTORY_A2 PAGE_P+2     
#define OSD_ATTR_NUM_PART_DIRECTORY_A3 PAGE_P+3     
#define OSD_ATTR_NUM_PART_DIRECTORY_A5 PAGE_P+5     
#define OSD_PAGE_NUM_UOBJ_DIRECTORY PAGE_U+0     
#define OSD_ATTR_NUM_UOBJ_DIRECTORY_page_id 0
#define OSD_ATTR_NUM_UOBJ_DIRECTORY_A1 PAGE_U+1     
#define OSD_ATTR_NUM_UOBJ_DIRECTORY_A2 PAGE_U+2     
#define OSD_ATTR_NUM_UOBJ_DIRECTORY_A3 PAGE_U+3     
#define OSD_ATTR_NUM_UOBJ_DIRECTORY_A4 PAGE_U+4     
#define OSD_ATTR_NUM_UOBJ_DIRECTORY_A5 PAGE_U+5     
#define OSD_PAGE_NUM_ROOT_INFO PAGE_R+1     
#define OSD_ATTR_NUM_ROOT_INFO_page_id 0
#define OSD_ATTR_NUM_ROOT_INFO_OSD_SYSTEM_ID 0x3     
#define OSD_ATTR_NUM_ROOT_INFO_VENDOR_ID 0x4     
#define OSD_ATTR_NUM_ROOT_INFO_PRODUCT_ID 0x5     
#define OSD_ATTR_NUM_ROOT_INFO_PRODUCT_MODEL 0x6     
#define OSD_ATTR_NUM_ROOT_INFO_PRODUCT_REVISION_LEVEL 0x7     
#define OSD_ATTR_NUM_ROOT_INFO_SERIAL_NUMBER 0x8     
#define OSD_ATTR_NUM_ROOT_INFO_OSD_NAME 0x9     
#define OSD_ATTR_NUM_ROOT_INFO_TOTAL_CAPACITY 0x80     
#define OSD_ATTR_NUM_ROOT_INFO_USED_CAPACITY 0x81     
#define OSD_ATTR_NUM_ROOT_INFO_NUM_OF_PARTITIONS 0xc0     
#define OSD_ATTR_NUM_ROOT_INFO_CLOCK 0x100     
#define OSD_PAGE_NUM_PART_INFO PAGE_P+1     
#define OSD_ATTR_NUM_PART_INFO_page_id 0
#define OSD_ATTR_NUM_PART_INFO_PARTITION_ID 0x1     
#define OSD_ATTR_NUM_PART_INFO_USERNAME 0x9     
#define OSD_ATTR_NUM_PART_INFO_USED_CAPACITY 0x81     
#define OSD_ATTR_NUM_PART_INFO_NUM_OF_OBJECTS 0xC1     
#define OSD_PAGE_NUM_UOBJ_INFO PAGE_U+0x1     
#define OSD_ATTR_NUM_UOBJ_INFO_page_id 0
#define OSD_ATTR_NUM_UOBJ_INFO_PARTITION_ID 0x1     
#define OSD_ATTR_NUM_UOBJ_INFO_OBJECT_ID 0x2     
#define OSD_ATTR_NUM_UOBJ_INFO_USERNAME 0x9     
#define OSD_ATTR_NUM_UOBJ_INFO_USED_CAPACITY 0x81     
#define OSD_ATTR_NUM_UOBJ_INFO_OBJ_LENGTH 0x82     
#define OSD_PAGE_NUM_T10_USER_OC_PRIV_INFO PAGE_U+0x10     
#define OSD_ATTR_NUM_T10_USER_OC_PRIV_INFO_page_id 0
#define OSD_ATTR_NUM_T10_USER_OC_PRIV_INFO_GENERAL0 0x1     
#define OSD_ATTR_NUM_T10_USER_OC_PRIV_INFO_GENERAL1 0x2     
#define OSD_ATTR_NUM_T10_USER_OC_PRIV_INFO_GENERAL2 0x3     
#define OSD_ATTR_NUM_T10_USER_OC_PRIV_INFO_GENERAL3 0x4     
#define OSD_ATTR_NUM_T10_USER_OC_PRIV_INFO_GENERAL4 0x5     
#define OSD_ATTR_NUM_T10_USER_OC_PRIV_INFO_DL_NEXT 0x6     
#define OSD_ATTR_NUM_T10_USER_OC_PRIV_INFO_DL_PREV 0x7     
#define OSD_ATTR_NUM_T10_USER_OC_PRIV_INFO_DEL_CURSOR 0x8     
#define OSD_PAGE_NUM_PART_OC_PRIV_INFO PAGE_P+0x10     
#define OSD_ATTR_NUM_PART_OC_PRIV_INFO_page_id 0
#define OSD_ATTR_NUM_PART_OC_PRIV_INFO_NUM_OBJECTS 0x2     
#define OSD_PAGE_NUM_ROOT_OC_PRIV_INFO PAGE_R+0x10     
#define OSD_ATTR_NUM_ROOT_OC_PRIV_INFO_page_id 0
#define OSD_ATTR_NUM_ROOT_OC_PRIV_INFO_TDLIST_ROOT_LBA 0x1     
#define OSD_PAGE_NUM_ROOT_QUOTAS PAGE_R+0x2     
#define OSD_ATTR_NUM_ROOT_QUOTAS_page_id 0
#define OSD_ATTR_NUM_ROOT_QUOTAS_DEFAULT_MAX_OBJ_LEN 0x1     
#define OSD_ATTR_NUM_ROOT_QUOTAS_PARTITION_CAPACITY_QUOTA 0x10001     
#define OSD_ATTR_NUM_ROOT_QUOTAS_PARTITION_OBJ_COUNT 0x10002     
#define OSD_ATTR_NUM_ROOT_QUOTAS_PARTITION_COLLECTIONS_PER_OBJ 0x10081     
#define OSD_ATTR_NUM_ROOT_QUOTAS_PARTITION_COUNT 0x20002     
#define OSD_PAGE_NUM_PART_QUOTAS PAGE_P+0x2     
#define OSD_ATTR_NUM_PART_QUOTAS_page_id 0
#define OSD_ATTR_NUM_PART_QUOTAS_DEFAULT_MAX_OBJ_LEN 0x1     
#define OSD_ATTR_NUM_PART_QUOTAS_CAPACITY_QUOTA 0x10001     
#define OSD_ATTR_NUM_PART_QUOTAS_OBJ_COUNT 0x10002     
#define OSD_ATTR_NUM_PART_QUOTAS_COLLECTIONS_PER_OBJ 0x10081     
#define OSD_PAGE_NUM_UOBJ_QUOTAS PAGE_U+0x2     
#define OSD_ATTR_NUM_UOBJ_QUOTAS_page_id 0
#define OSD_ATTR_NUM_UOBJ_QUOTAS_MAX_OBJ_LEN 0x1     
#define OSD_PAGE_NUM_ROOT_TIMESTAMPS PAGE_R+0x3     
#define OSD_ATTR_NUM_ROOT_TIMESTAMPS_page_id 0
#define OSD_ATTR_NUM_ROOT_TIMESTAMPS_ATTR_ACCESSED_TIME 0x2     
#define OSD_ATTR_NUM_ROOT_TIMESTAMPS_ATTR_MODIFIED_TIME 0x3     
#define OSD_ATTR_NUM_ROOT_TIMESTAMPS_TIMESTAMP_BYPASS 0xfffffffe     
#define OSD_PAGE_NUM_PART_TIMESTAMPS PAGE_P+0x3     
#define OSD_ATTR_NUM_PART_TIMESTAMPS_page_id 0
#define OSD_ATTR_NUM_PART_TIMESTAMPS_CREATED_TIME 0x1     
#define OSD_ATTR_NUM_PART_TIMESTAMPS_ATTR_ACCESSED_TIME 0x2     
#define OSD_ATTR_NUM_PART_TIMESTAMPS_ATTR_MODIFIED_TIME 0x3     
#define OSD_ATTR_NUM_PART_TIMESTAMPS_DATA_ACCESSED_TIME 0x4     
#define OSD_ATTR_NUM_PART_TIMESTAMPS_DATA_MODIFIED_TIME 0x5     
#define OSD_ATTR_NUM_PART_TIMESTAMPS_TIMESTAMP_BYPASS 0xfffffffe     
#define OSD_PAGE_NUM_UOBJ_TIMESTAMPS PAGE_U+0x3     
#define OSD_ATTR_NUM_UOBJ_TIMESTAMPS_page_id 0
#define OSD_ATTR_NUM_UOBJ_TIMESTAMPS_CREATED_TIME 0x1     
#define OSD_ATTR_NUM_UOBJ_TIMESTAMPS_ATTR_ACCESSED_TIME 0x2     
#define OSD_ATTR_NUM_UOBJ_TIMESTAMPS_ATTR_MODIFIED_TIME 0x3     
#define OSD_ATTR_NUM_UOBJ_TIMESTAMPS_DATA_ACCESSED_TIME 0x4     
#define OSD_ATTR_NUM_UOBJ_TIMESTAMPS_DATA_MODIFIED_TIME 0x5     
#define OSD_PAGE_NUM_T10_COLLECTIONS PAGE_U+0x4     
#define OSD_ATTR_NUM_T10_COLLECTIONS_page_id 0
#define OSD_PAGE_NUM_ROOT_SECURITY PAGE_R+0x5     
#define OSD_ATTR_NUM_ROOT_SECURITY_page_id 0
#define OSD_ATTR_NUM_ROOT_SECURITY_DEFAULT_SEC_METHOD 0x1     
#define OSD_ATTR_NUM_ROOT_SECURITY_PARTITION_DEFAULT_SEC_METHOD 0x6     
#define OSD_ATTR_NUM_ROOT_SECURITY_SUPPORTED_SEC_METHODS 0x7     
#define OSD_ATTR_NUM_ROOT_SECURITY_OLDEST_VALID_NONCE 0x2     
#define OSD_ATTR_NUM_ROOT_SECURITY_NEWEST_VALID_NONCE 0x3     
#define OSD_ATTR_NUM_ROOT_SECURITY_ADJUSTABLE_CLOCK 0x9     
#define OSD_ATTR_NUM_ROOT_SECURITY_MASTER_KEY_ID 0x7FFD     
#define OSD_ATTR_NUM_ROOT_SECURITY_ROOT_KEY_ID 0x7FFE     
#define OSD_ATTR_NUM_ROOT_SECURITY_ALG_1 0x80000000+0     
#define OSD_ATTR_NUM_ROOT_SECURITY_ALG_2 0x80000000+1     
#define OSD_ATTR_NUM_ROOT_SECURITY_ALG_3 0x80000000+2     
#define OSD_ATTR_NUM_ROOT_SECURITY_ALG_4 0x80000000+3     
#define OSD_ATTR_NUM_ROOT_SECURITY_ALG_5 0x80000000+4     
#define OSD_ATTR_NUM_ROOT_SECURITY_ALG_6 0x80000000+5     
#define OSD_ATTR_NUM_ROOT_SECURITY_ALG_7 0x80000000+6     
#define OSD_ATTR_NUM_ROOT_SECURITY_ALG_8 0x80000000+7     
#define OSD_ATTR_NUM_ROOT_SECURITY_ALG_9 0x80000000+8     
#define OSD_ATTR_NUM_ROOT_SECURITY_ALG_10 0x80000000+9     
#define OSD_ATTR_NUM_ROOT_SECURITY_ALG_11 0x80000000+10     
#define OSD_ATTR_NUM_ROOT_SECURITY_ALG_12 0x80000000+11     
#define OSD_ATTR_NUM_ROOT_SECURITY_ALG_13 0x80000000+12     
#define OSD_ATTR_NUM_ROOT_SECURITY_ALG_14 0x80000000+13     
#define OSD_ATTR_NUM_ROOT_SECURITY_ALG_15 0x80000000+14     
#define OSD_ATTR_NUM_ROOT_SECURITY_ALG_16 0x80000000+15     
#define OSD_ATTR_NUM_ROOT_SECURITY_DH_GROUP_1 0x80000010+0     
#define OSD_ATTR_NUM_ROOT_SECURITY_DH_GROUP_2 0x80000010+1     
#define OSD_ATTR_NUM_ROOT_SECURITY_DH_GROUP_3 0x80000010+2     
#define OSD_ATTR_NUM_ROOT_SECURITY_DH_GROUP_4 0x80000010+3     
#define OSD_ATTR_NUM_ROOT_SECURITY_DH_GROUP_5 0x80000010+4     
#define OSD_ATTR_NUM_ROOT_SECURITY_DH_GROUP_6 0x80000010+5     
#define OSD_ATTR_NUM_ROOT_SECURITY_DH_GROUP_7 0x80000010+6     
#define OSD_ATTR_NUM_ROOT_SECURITY_DH_GROUP_8 0x80000010+7     
#define OSD_ATTR_NUM_ROOT_SECURITY_DH_GROUP_9 0x80000010+8     
#define OSD_ATTR_NUM_ROOT_SECURITY_DH_GROUP_10 0x80000010+9     
#define OSD_ATTR_NUM_ROOT_SECURITY_DH_GROUP_11 0x80000010+10     
#define OSD_ATTR_NUM_ROOT_SECURITY_DH_GROUP_12 0x80000010+11     
#define OSD_ATTR_NUM_ROOT_SECURITY_DH_GROUP_13 0x80000010+12     
#define OSD_ATTR_NUM_ROOT_SECURITY_DH_GROUP_14 0x80000010+13     
#define OSD_ATTR_NUM_ROOT_SECURITY_DH_GROUP_15 0x80000010+14     
#define OSD_ATTR_NUM_ROOT_SECURITY_DH_GROUP_16 0x80000010+15     
#define OSD_PAGE_NUM_PART_SECURITY PAGE_P+0x5     
#define OSD_ATTR_NUM_PART_SECURITY_page_id 0
#define OSD_ATTR_NUM_PART_SECURITY_DEFAULT_SEC_METHOD 0x1     
#define OSD_ATTR_NUM_PART_SECURITY_OLDEST_VALID_NONCE 0x2     
#define OSD_ATTR_NUM_PART_SECURITY_NEWEST_VALID_NONCE 0x3     
#define OSD_ATTR_NUM_PART_SECURITY_REQ_NONCE_LIST_DEPTH 0x4     
#define OSD_ATTR_NUM_PART_SECURITY_FROZEN_KEYS_MASK 0x5     
#define OSD_ATTR_NUM_PART_SECURITY_PARTITION_KEY_ID 0x7FFF     
#define OSD_ATTR_NUM_PART_SECURITY_WORKING_KEY_ID_0 0x8000+0     
#define OSD_ATTR_NUM_PART_SECURITY_WORKING_KEY_ID_1 0x8000+1     
#define OSD_ATTR_NUM_PART_SECURITY_WORKING_KEY_ID_2 0x8000+2     
#define OSD_ATTR_NUM_PART_SECURITY_WORKING_KEY_ID_3 0x8000+3     
#define OSD_ATTR_NUM_PART_SECURITY_WORKING_KEY_ID_4 0x8000+4     
#define OSD_ATTR_NUM_PART_SECURITY_WORKING_KEY_ID_5 0x8000+5     
#define OSD_ATTR_NUM_PART_SECURITY_WORKING_KEY_ID_6 0x8000+6     
#define OSD_ATTR_NUM_PART_SECURITY_WORKING_KEY_ID_7 0x8000+7     
#define OSD_ATTR_NUM_PART_SECURITY_WORKING_KEY_ID_8 0x8000+8     
#define OSD_ATTR_NUM_PART_SECURITY_WORKING_KEY_ID_9 0x8000+9     
#define OSD_ATTR_NUM_PART_SECURITY_WORKING_KEY_ID_10 0x8000+10     
#define OSD_ATTR_NUM_PART_SECURITY_WORKING_KEY_ID_11 0x8000+11     
#define OSD_ATTR_NUM_PART_SECURITY_WORKING_KEY_ID_12 0x8000+12     
#define OSD_ATTR_NUM_PART_SECURITY_WORKING_KEY_ID_13 0x8000+13     
#define OSD_ATTR_NUM_PART_SECURITY_WORKING_KEY_ID_14 0x8000+14     
#define OSD_ATTR_NUM_PART_SECURITY_WORKING_KEY_ID_15 0x8000+15     
#define OSD_ATTR_NUM_PART_SECURITY_POLICY_ACCESS_TAG 0x40000001     
#define OSD_ATTR_NUM_PART_SECURITY_USER_OBJ_POLICY_ACCESS_TAG 0x40000002     
#define OSD_PAGE_NUM_UOBJ_SECURITY PAGE_U+0x5     
#define OSD_ATTR_NUM_UOBJ_SECURITY_page_id 0
#define OSD_ATTR_NUM_UOBJ_SECURITY_POLICY_ACCESS_TAG 0x40000001     
#define OSD_PAGE_NUM_CUR_CMD PAGE_A+0xFFFFFFE     
#define OSD_ATTR_NUM_CUR_CMD_page_id 0
#define OSD_ATTR_NUM_CUR_CMD_RESPONSE_INT_CHECK_VAL 0x1     
#define OSD_ATTR_NUM_CUR_CMD_OBJ_TYPE 0x2     
#define OSD_ATTR_NUM_CUR_CMD_PARTITION_ID 0x3     
#define OSD_ATTR_NUM_CUR_CMD_OBJ_ID 0x4     
#define OSD_ATTR_NUM_CUR_CMD_APPEND_STARTING_BYTE 0x5     
#define OSD_PAGE_NUM_IBM_ROOT_KEYS PAGE_R+PAGE_T_VND+1     
#define OSD_ATTR_NUM_IBM_ROOT_KEYS_page_id 0
#define OSD_ATTR_NUM_IBM_ROOT_KEYS_MASTER_AUTH_KEY 1     
#define OSD_ATTR_NUM_IBM_ROOT_KEYS_MASTER_GEN_KEY 2     
#define OSD_ATTR_NUM_IBM_ROOT_KEYS_ROOT_AUTH_KEY 3     
#define OSD_ATTR_NUM_IBM_ROOT_KEYS_ROOT_GEN_KEY 4     
#define OSD_PAGE_NUM_IBM_PART_KEYS PAGE_P+PAGE_T_VND+2     
#define OSD_ATTR_NUM_IBM_PART_KEYS_page_id 0
#define OSD_ATTR_NUM_IBM_PART_KEYS_PART_AUTH_KEY 5     
#define OSD_ATTR_NUM_IBM_PART_KEYS_PART_GEN_KEY 6     
#define OSD_ATTR_NUM_IBM_PART_KEYS_WORK_KEY_0 0x10     
#define OSD_ATTR_NUM_IBM_PART_KEYS_WORK_KEY_1 0x11     
#define OSD_ATTR_NUM_IBM_PART_KEYS_WORK_KEY_2 0x12     
#define OSD_ATTR_NUM_IBM_PART_KEYS_WORK_KEY_3 0x13     
#define OSD_ATTR_NUM_IBM_PART_KEYS_WORK_KEY_4 0x14     
#define OSD_ATTR_NUM_IBM_PART_KEYS_WORK_KEY_5 0x15     
#define OSD_ATTR_NUM_IBM_PART_KEYS_WORK_KEY_6 0x16     
#define OSD_ATTR_NUM_IBM_PART_KEYS_WORK_KEY_7 0x17     
#define OSD_ATTR_NUM_IBM_PART_KEYS_WORK_KEY_8 0x18     
#define OSD_ATTR_NUM_IBM_PART_KEYS_WORK_KEY_9 0x19     
#define OSD_ATTR_NUM_IBM_PART_KEYS_WORK_KEY_10 0x1A     
#define OSD_ATTR_NUM_IBM_PART_KEYS_WORK_KEY_11 0x1B     
#define OSD_ATTR_NUM_IBM_PART_KEYS_WORK_KEY_12 0x1C     
#define OSD_ATTR_NUM_IBM_PART_KEYS_WORK_KEY_13 0x1D     
#define OSD_ATTR_NUM_IBM_PART_KEYS_WORK_KEY_14 0x1E     
#define OSD_ATTR_NUM_IBM_PART_KEYS_WORK_KEY_15 0x1F     
#define OSD_PAGE_NUM_IBM_UOBJ_FS_DATA PAGE_U+PAGE_T_VND+3     
#define OSD_ATTR_NUM_IBM_UOBJ_FS_DATA_page_id 0
#define OSD_ATTR_NUM_IBM_UOBJ_FS_DATA_INODE 1     
